import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import5 from './games';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import16 from '@angular/core/src/linker/component_factory';
export declare const GamesPageNgFactory: import16.ComponentFactory<import5.GamesPage>;
export declare function viewFactory_GamesPage0(viewUtils: import6.ViewUtils, parentInjector: import7.Injector, declarationEl: import2.AppElement): import1.AppView<import5.GamesPage>;
export declare const GamesDetailNgFactory: import16.ComponentFactory<import5.GamesDetail>;
export declare function viewFactory_GamesDetail0(viewUtils: import6.ViewUtils, parentInjector: import7.Injector, declarationEl: import2.AppElement): import1.AppView<import5.GamesDetail>;
