/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../providers/player-service';
import * as import4 from '../../providers/game-service';
import * as import5 from './game-insert';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/navigation/view-controller';
import * as import12 from 'ionic-angular/components/toast/toast';
import * as import13 from 'ionic-angular/components/loading/loading';
import * as import14 from 'ionic-angular/components/alert/alert';
import * as import15 from 'ionic-angular/components/modal/modal';
import * as import16 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import17 from 'ionic-angular/navigation/nav-params';
import * as import18 from '@angular/core/src/metadata/view';
import * as import19 from '@angular/core/src/linker/component_factory';
import * as import20 from 'ionic-angular/components/toolbar/toolbar';
import * as import21 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import22 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from 'ionic-angular/components/button/button';
import * as import25 from 'ionic-angular/components/show-hide-when/show-hide-when';
import * as import26 from 'ionic-angular/components/typography/typography';
import * as import27 from 'ionic-angular/components/icon/icon';
import * as import28 from 'ionic-angular/components/content/content';
import * as import29 from 'ionic-angular/components/card/card';
import * as import30 from 'ionic-angular/components/item/item';
import * as import31 from 'ionic-angular/components/label/label';
import * as import32 from '@angular/forms/src/directives/ng_model';
import * as import33 from '@angular/forms/src/directives/ng_control_status';
import * as import34 from 'ionic-angular/components/input/input';
import * as import35 from 'ionic-angular/components/datetime/datetime';
import * as import36 from 'ionic-angular/components/item/item-reorder';
import * as import37 from 'ionic-angular/components/list/list';
import * as import38 from '@angular/common/src/directives/ng_for';
import * as import39 from 'ionic-angular/config/config';
import * as import40 from '@angular/core/src/linker/element_ref';
import * as import41 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import42 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import43 from 'ionic-angular/components/navbar/navbar';
import * as import44 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import45 from 'ionic-angular/platform/platform';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import48 from 'ionic-angular/components/app/app';
import * as import49 from 'ionic-angular/util/keyboard';
import * as import50 from 'ionic-angular/components/tabs/tabs';
import * as import51 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import52 from 'ionic-angular/util/form';
import * as import53 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import54 from 'ionic-angular/navigation/nav-controller';
import * as import55 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import56 from 'ionic-angular/components/picker/picker';
import * as import57 from 'ionic-angular/gestures/gesture-controller';
import * as import58 from '@angular/core/src/linker/template_ref';
import * as import59 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import60 from '@angular/forms/src/directives/ng_control';
import * as import61 from '@angular/forms/src/directives/control_value_accessor';
import * as import62 from 'ionic-angular/components/item/item-sliding';
import * as import63 from '@angular/common/src/directives/ng_class';
import * as import64 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
import * as import65 from '@angular/core/src/change_detection/differs/keyvalue_differs';
var renderType_GameInsert_Host:import0.RenderComponentType = (null as any);
class _View_GameInsert_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PlayerService_0_4:import3.PlayerService;
  _GameService_0_5:import4.GameService;
  _GameInsert_0_6:import5.GameInsert;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GameInsert_Host0,renderType_GameInsert_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_GameInsert0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PlayerService_0_4 = new import3.PlayerService(this.parentInjector.get(import10.Http));
    this._GameService_0_5 = new import4.GameService(this.parentInjector.get(import10.Http));
    this._GameInsert_0_6 = new import5.GameInsert(this.parentInjector.get(import11.ViewController),this._PlayerService_0_4,this.parentInjector.get(import12.ToastController),this.parentInjector.get(import13.LoadingController),this._GameService_0_5,this.parentInjector.get(import14.AlertController),this.parentInjector.get(import15.ModalController),this.parentInjector.get(import16.ActionSheetController),this.parentInjector.get(import17.NavParams));
    this._appEl_0.initComponent(this._GameInsert_0_6,[],compView_0);
    compView_0.create(this._GameInsert_0_6,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PlayerService) && (0 === requestNodeIndex))) { return this._PlayerService_0_4; }
    if (((token === import4.GameService) && (0 === requestNodeIndex))) { return this._GameService_0_5; }
    if (((token === import5.GameInsert) && (0 === requestNodeIndex))) { return this._GameInsert_0_6; }
    return notFoundResult;
  }
}
function viewFactory_GameInsert_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_GameInsert_Host === (null as any))) { (renderType_GameInsert_Host = viewUtils.createRenderComponentType('',0,import18.ViewEncapsulation.None,[],{})); }
  return new _View_GameInsert_Host0(viewUtils,parentInjector,declarationEl);
}
export const GameInsertNgFactory:import19.ComponentFactory<import5.GameInsert> = new import19.ComponentFactory<import5.GameInsert>('ng-component',viewFactory_GameInsert_Host0,import5.GameInsert);
const styles_GameInsert:any[] = [];
var renderType_GameInsert:import0.RenderComponentType = (null as any);
class _View_GameInsert0 extends import1.AppView<import5.GameInsert> {
  _el_0:any;
  _Header_0_3:import20.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Toolbar_2_4:import20.Toolbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import21.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import22.ToolbarItem;
  _query_Button_7_0:import23.QueryList<any>;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Button_9_4:import24.Button;
  _text_10:any;
  _el_11:any;
  _ShowWhen_11_3:import25.ShowWhen;
  _Typography_11_4:import26.Typography;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _Icon_14_3:import27.Icon;
  _ShowWhen_14_4:import25.ShowWhen;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Content_20_4:import28.Content;
  _text_21:any;
  _el_22:any;
  _Card_22_3:import29.Card;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Item_24_4:import30.Item;
  _ItemContent_24_5:import30.ItemContent;
  _query_Label_24_0:import23.QueryList<any>;
  _query_Button_24_1:import23.QueryList<any>;
  _query_Icon_24_2:import23.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _Label_26_3:import31.Label;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _NgModel_29_4:import32.NgModel;
  _NgControl_29_5:any;
  _NgControlStatus_29_6:import33.NgControlStatus;
  _TextInput_29_7:import34.TextInput;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Item_32_4:import30.Item;
  _ItemContent_32_5:import30.ItemContent;
  _query_Label_32_0:import23.QueryList<any>;
  _query_Button_32_1:import23.QueryList<any>;
  _query_Icon_32_2:import23.QueryList<any>;
  _text_33:any;
  _el_34:any;
  _Label_34_3:import31.Label;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _DateTime_37_4:import35.DateTime;
  _NG_VALUE_ACCESSOR_37_5:any[];
  _NgModel_37_6:import32.NgModel;
  _NgControl_37_7:any;
  _NgControlStatus_37_8:import33.NgControlStatus;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _Card_41_3:import29.Card;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _Item_43_4:import30.Item;
  _ItemContent_43_5:import30.ItemContent;
  _query_Label_43_0:import23.QueryList<any>;
  _query_Button_43_1:import23.QueryList<any>;
  _query_Icon_43_2:import23.QueryList<any>;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _ItemReorder_55_3:import36.ItemReorder;
  _List_55_4:import37.List;
  _text_56:any;
  _anchor_57:any;
  /*private*/ _appEl_57:import2.AppElement;
  _TemplateRef_57_5:any;
  _NgFor_57_6:import38.NgFor;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _Footer_61_3:import20.Footer;
  _text_62:any;
  _el_63:any;
  /*private*/ _appEl_63:import2.AppElement;
  _Button_63_4:import24.Button;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  /*private*/ _appEl_66:import2.AppElement;
  _Button_66_4:import24.Button;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_40:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GameInsert0,renderType_GameInsert,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import20.Header(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import11.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import41.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import20.Toolbar(this.parentInjector.get(import11.ViewController,(null as any)),this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import42.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import21.ToolbarTitle(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_4),this.renderer,this._Toolbar_2_4,this.parentInjector.get(import43.Navbar,(null as any)));
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Nova rodada',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_7,'end','');
    this._ToolbarItem_7_3 = new import22.ToolbarItem(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_7),this.renderer,this._Toolbar_2_4,this.parentInjector.get(import43.Navbar,(null as any)));
    this._query_Button_7_0 = new import23.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'ion-button','');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import44.viewFactory_Button0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Button_9_4 = new import24.Button((null as any),'',this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_9),this.renderer);
    this._appEl_9.initComponent(this._Button_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_11,'color','primary');
    this.renderer.setElementAttribute(this._el_11,'showWhen','ios');
    this._ShowWhen_11_3 = new import25.ShowWhen('ios',this.parentInjector.get(import45.Platform),this.parentInjector.get(import46.NgZone));
    this._Typography_11_4 = new import26.Typography(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_11,'Cancel',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_14,'name','md-close');
    this.renderer.setElementAttribute(this._el_14,'role','img');
    this.renderer.setElementAttribute(this._el_14,'showWhen','android,windows');
    this._Icon_14_3 = new import27.Icon(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_14),this.renderer);
    this._ShowWhen_14_4 = new import25.ShowWhen('android,windows',this.parentInjector.get(import45.Platform),this.parentInjector.get(import46.NgZone));
    this._text_15 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_9.create(this._Button_9_4,[[].concat([
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_15
      ]
    )],(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [].concat([this._el_7]),
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_17
      ]
      )
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_20 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_20 = new import2.AppElement(20,(null as any),this,this._el_20);
    var compView_20:any = import47.viewFactory_Content0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Content_20_4 = new import28.Content(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import48.App),this.parentInjector.get(import49.Keyboard),this.parentInjector.get(import46.NgZone),this.parentInjector.get(import11.ViewController,(null as any)),this.parentInjector.get(import50.Tabs,(null as any)));
    this._appEl_20.initComponent(this._Content_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_22_3 = new import29.Card(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText(this._el_22,'\n		',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this._appEl_24 = new import2.AppElement(24,22,this,this._el_24);
    var compView_24:any = import51.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import30.Item(this.parentInjector.get(import52.Form),this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_24),this.renderer);
    this._ItemContent_24_5 = new import30.ItemContent();
    this._query_Label_24_0 = new import23.QueryList<any>();
    this._query_Button_24_1 = new import23.QueryList<any>();
    this._query_Icon_24_2 = new import23.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_26,'fixed','');
    this._Label_26_3 = new import31.Label(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_26),this.renderer,(null as any),(null as any),'',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Descrição',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_29,'type','text');
    this._appEl_29 = new import2.AppElement(29,24,this,this._el_29);
    var compView_29:any = import53.viewFactory_TextInput0(this.viewUtils,this.injector(29),this._appEl_29);
    this._NgModel_29_4 = new import32.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_29_5 = this._NgModel_29_4;
    this._NgControlStatus_29_6 = new import33.NgControlStatus(this._NgControl_29_5);
    this._TextInput_29_7 = new import34.TextInput(this.parentInjector.get(import39.Config),this.parentInjector.get(import52.Form),this._Item_24_4,this.parentInjector.get(import48.App),this.parentInjector.get(import45.Platform),new import40.ElementRef(this._el_29),this.renderer,this._Content_20_4,this.parentInjector.get(import54.NavController,(null as any)),this._NgControl_29_5);
    this._appEl_29.initComponent(this._TextInput_29_7,[],compView_29);
    compView_29.create(this._TextInput_29_7,[],(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_24_0.reset([this._Label_26_3]);
    this._Item_24_4.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4,[
      [],
      [].concat([this._el_26]),
      [].concat([
        this._text_25,
        this._text_28,
        this._text_30
      ]
      ),
      [].concat([this._el_29]),
      []
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_22,'\n		',(null as any));
    this._el_32 = this.renderer.createElement(this._el_22,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','item item-block');
    this._appEl_32 = new import2.AppElement(32,22,this,this._el_32);
    var compView_32:any = import51.viewFactory_Item0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Item_32_4 = new import30.Item(this.parentInjector.get(import52.Form),this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_32),this.renderer);
    this._ItemContent_32_5 = new import30.ItemContent();
    this._query_Label_32_0 = new import23.QueryList<any>();
    this._query_Button_32_1 = new import23.QueryList<any>();
    this._query_Icon_32_2 = new import23.QueryList<any>();
    this._appEl_32.initComponent(this._Item_32_4,[],compView_32);
    this._text_33 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_34,'fixed','');
    this._Label_34_3 = new import31.Label(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_34),this.renderer,(null as any),(null as any),'',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Data',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_37,'displayFormat','DD/MM/YYYY');
    this._appEl_37 = new import2.AppElement(37,32,this,this._el_37);
    var compView_37:any = import55.viewFactory_DateTime0(this.viewUtils,this.injector(37),this._appEl_37);
    this._DateTime_37_4 = new import35.DateTime(this.parentInjector.get(import52.Form),this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_37),this.renderer,this._Item_32_4,this.parentInjector.get(import56.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_37_5 = [this._DateTime_37_4];
    this._NgModel_37_6 = new import32.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_37_5);
    this._NgControl_37_7 = this._NgModel_37_6;
    this._NgControlStatus_37_8 = new import33.NgControlStatus(this._NgControl_37_7);
    this._appEl_37.initComponent(this._DateTime_37_4,[],compView_37);
    compView_37.create(this._DateTime_37_4,[],(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_32_0.reset([this._Label_34_3]);
    this._Item_32_4.contentLabel = this._query_Label_32_0.first;
    compView_32.create(this._Item_32_4,[
      [],
      [].concat([this._el_34]),
      [].concat([
        this._text_33,
        this._text_36,
        this._text_38
      ]
      ),
      [].concat([this._el_37]),
      []
    ]
    ,(null as any));
    this._text_39 = this.renderer.createText(this._el_22,'\n	',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_41_3 = new import29.Card(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText(this._el_41,'\n		',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','item item-block');
    this._appEl_43 = new import2.AppElement(43,41,this,this._el_43);
    var compView_43:any = import51.viewFactory_Item0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Item_43_4 = new import30.Item(this.parentInjector.get(import52.Form),this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_43),this.renderer);
    this._ItemContent_43_5 = new import30.ItemContent();
    this._query_Label_43_0 = new import23.QueryList<any>();
    this._query_Button_43_1 = new import23.QueryList<any>();
    this._query_Icon_43_2 = new import23.QueryList<any>();
    this._appEl_43.initComponent(this._Item_43_4,[],compView_43);
    this._el_44 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_43_0.reset([]);
    this._Item_43_4.contentLabel = this._query_Label_43_0.first;
    compView_43.create(this._Item_43_4,[
      [],
      [],
      [].concat([
        this._el_44,
        this._text_46,
        this._el_47,
        this._text_49,
        this._el_50,
        this._text_52
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_53 = this.renderer.createText(this._el_41,'	\n\n	',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_55,'reorder','true');
    this._ItemReorder_55_3 = new import36.ItemReorder(new import40.ElementRef(this._el_55),this.renderer,this.parentInjector.get(import46.NgZone),this._Content_20_4);
    this._List_55_4 = new import37.List(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_55),this.renderer,this.parentInjector.get(import57.GestureController));
    this._text_56 = this.renderer.createText(this._el_55,'\n		',(null as any));
    this._anchor_57 = this.renderer.createTemplateAnchor(this._el_55,(null as any));
    this._appEl_57 = new import2.AppElement(57,55,this,this._anchor_57);
    this._TemplateRef_57_5 = new import58.TemplateRef_(this._appEl_57,viewFactory_GameInsert1);
    this._NgFor_57_6 = new import38.NgFor(this._appEl_57.vcRef,this._TemplateRef_57_5,this.parentInjector.get(import59.IterableDiffers),this.ref);
    this._text_58 = this.renderer.createText(this._el_55,'\n	',(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_20.create(this._Content_20_4,[
      [],
      [].concat([
        this._text_21,
        this._el_22,
        this._text_40,
        this._el_41,
        this._text_54,
        this._el_55,
        this._text_59
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_60 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_61 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this._Footer_61_3 = new import20.Footer(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_61),this.renderer,this.parentInjector.get(import11.ViewController,(null as any)));
    this._text_62 = this.renderer.createText(this._el_61,'\n	',(null as any));
    this._el_63 = this.renderer.createElement(this._el_61,'button',(null as any));
    this.renderer.setElementAttribute(this._el_63,'full','');
    this.renderer.setElementAttribute(this._el_63,'ion-button','');
    this._appEl_63 = new import2.AppElement(63,61,this,this._el_63);
    var compView_63:any = import44.viewFactory_Button0(this.viewUtils,this.injector(63),this._appEl_63);
    this._Button_63_4 = new import24.Button((null as any),'',this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_63),this.renderer);
    this._appEl_63.initComponent(this._Button_63_4,[],compView_63);
    this._text_64 = this.renderer.createText((null as any),'Salvar',(null as any));
    compView_63.create(this._Button_63_4,[[].concat([this._text_64])],(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n	',(null as any));
    this._el_66 = this.renderer.createElement(this._el_61,'button',(null as any));
    this.renderer.setElementAttribute(this._el_66,'full','');
    this.renderer.setElementAttribute(this._el_66,'ion-button','');
    this._appEl_66 = new import2.AppElement(66,61,this,this._el_66);
    var compView_66:any = import44.viewFactory_Button0(this.viewUtils,this.injector(66),this._appEl_66);
    this._Button_66_4 = new import24.Button((null as any),'',this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_66),this.renderer);
    this._appEl_66.initComponent(this._Button_66_4,[],compView_66);
    this._text_67 = this.renderer.createText((null as any),'Preview',(null as any));
    compView_66.create(this._Button_66_4,[[].concat([this._text_67])],(null as any));
    this._text_68 = this.renderer.createText(this._el_61,'\n',(null as any));
    this._text_69 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this._expr_5 = import9.UNINITIALIZED;
    this._expr_6 = import9.UNINITIALIZED;
    this._expr_7 = import9.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_29,'ngModelChange',this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    this._expr_9 = import9.UNINITIALIZED;
    const subscription_0:any = this._NgModel_29_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    this._expr_10 = import9.UNINITIALIZED;
    this._expr_11 = import9.UNINITIALIZED;
    this._expr_12 = import9.UNINITIALIZED;
    this._expr_13 = import9.UNINITIALIZED;
    this._expr_14 = import9.UNINITIALIZED;
    this._expr_15 = import9.UNINITIALIZED;
    this._expr_16 = import9.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_37,'ngModelChange',this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_37,'keyup.space',this.eventHandler(this._handle_keyup_space_37_2.bind(this)));
    this._expr_20 = import9.UNINITIALIZED;
    this._expr_21 = import9.UNINITIALIZED;
    this._expr_22 = import9.UNINITIALIZED;
    const subscription_1:any = this._NgModel_37_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    this._expr_23 = import9.UNINITIALIZED;
    this._expr_24 = import9.UNINITIALIZED;
    this._expr_25 = import9.UNINITIALIZED;
    this._expr_26 = import9.UNINITIALIZED;
    this._expr_27 = import9.UNINITIALIZED;
    this._expr_28 = import9.UNINITIALIZED;
    this._expr_29 = import9.UNINITIALIZED;
    this._expr_30 = import9.UNINITIALIZED;
    this._expr_31 = import9.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_55,'ionItemReorder',this.eventHandler(this._handle_ionItemReorder_55_0.bind(this)));
    this._expr_33 = import9.UNINITIALIZED;
    this._expr_34 = import9.UNINITIALIZED;
    this._expr_35 = import9.UNINITIALIZED;
    const subscription_2:any = this._ItemReorder_55_3.ionItemReorder.subscribe(this.eventHandler(this._handle_ionItemReorder_55_0.bind(this)));
    this._expr_36 = import9.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_63,'click',this.eventHandler(this._handle_click_63_0.bind(this)));
    this._expr_38 = import9.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_66,'click',this.eventHandler(this._handle_click_66_0.bind(this)));
    this._expr_40 = import9.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._anchor_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._text_69
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import25.ShowWhen) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ShowWhen_11_3; }
    if (((token === import26.Typography) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Typography_11_4; }
    if (((token === import27.Icon) && (14 === requestNodeIndex))) { return this._Icon_14_3; }
    if (((token === import25.ShowWhen) && (14 === requestNodeIndex))) { return this._ShowWhen_14_4; }
    if (((token === import24.Button) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Button_9_4; }
    if (((token === import22.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ToolbarItem_7_3; }
    if (((token === import20.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Toolbar_2_4; }
    if (((token === import20.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Header_0_3; }
    if (((token === import31.Label) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Label_26_3; }
    if (((token === import32.NgModel) && (29 === requestNodeIndex))) { return this._NgModel_29_4; }
    if (((token === import60.NgControl) && (29 === requestNodeIndex))) { return this._NgControl_29_5; }
    if (((token === import33.NgControlStatus) && (29 === requestNodeIndex))) { return this._NgControlStatus_29_6; }
    if (((token === import34.TextInput) && (29 === requestNodeIndex))) { return this._TextInput_29_7; }
    if (((token === import30.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_24_4; }
    if (((token === import30.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ItemContent_24_5; }
    if (((token === import31.Label) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Label_34_3; }
    if (((token === import35.DateTime) && (37 === requestNodeIndex))) { return this._DateTime_37_4; }
    if (((token === import61.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_5; }
    if (((token === import32.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_6; }
    if (((token === import60.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_7; }
    if (((token === import33.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_8; }
    if (((token === import30.Item) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Item_32_4; }
    if (((token === import30.ItemContent) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ItemContent_32_5; }
    if (((token === import29.Card) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Card_22_3; }
    if (((token === import30.Item) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Item_43_4; }
    if (((token === import30.ItemContent) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ItemContent_43_5; }
    if (((token === import29.Card) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Card_41_3; }
    if (((token === import58.TemplateRef) && (57 === requestNodeIndex))) { return this._TemplateRef_57_5; }
    if (((token === import38.NgFor) && (57 === requestNodeIndex))) { return this._NgFor_57_6; }
    if (((token === import36.ItemReorder) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ItemReorder_55_3; }
    if (((token === import37.List) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._List_55_4; }
    if (((token === import28.Content) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Content_20_4; }
    if (((token === import24.Button) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Button_63_4; }
    if (((token === import24.Button) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Button_66_4; }
    if (((token === import20.Footer) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Footer_61_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    const currVal_3:any = 'primary';
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Typography_11_4.color = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = 'md-close';
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_14_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_20_4.ngOnInit(); }
    changes = (null as any);
    const currVal_9:any = this.context.game.description;
    if (import6.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgModel_29_4.model = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import9.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgModel_29_4.ngOnChanges(changes); }
    const currVal_16:any = 'text';
    if (import6.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._TextInput_29_7.type = currVal_16;
      this._expr_16 = currVal_16;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_29_7.ngOnInit(); }
    const currVal_20:any = 'DD/MM/YYYY';
    if (import6.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._DateTime_37_4.displayFormat = currVal_20;
      this._expr_20 = currVal_20;
    }
    changes = (null as any);
    const currVal_22:any = this.context.game.date;
    if (import6.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._NgModel_37_6.model = currVal_22;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import9.SimpleChange(this._expr_22,currVal_22);
      this._expr_22 = currVal_22;
    }
    if ((changes !== (null as any))) { this._NgModel_37_6.ngOnChanges(changes); }
    const currVal_33:any = 'true';
    if (import6.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._ItemReorder_55_3.reorder = currVal_33;
      this._expr_33 = currVal_33;
    }
    changes = (null as any);
    const currVal_36:any = this.context.players;
    if (import6.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._NgFor_57_6.ngForOf = currVal_36;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_36,currVal_36);
      this._expr_36 = currVal_36;
    }
    if ((changes !== (null as any))) { this._NgFor_57_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_57_6.ngDoCheck(); }
    changed = false;
    const currVal_38:any = '';
    if (import6.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._Button_63_4.full = currVal_38;
      changed = true;
      this._expr_38 = currVal_38;
    }
    if (changed) { this._appEl_63.componentView.markAsCheckOnce(); }
    changed = false;
    const currVal_40:any = '';
    if (import6.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._Button_66_4.full = currVal_40;
      changed = true;
      this._expr_40 = currVal_40;
    }
    if (changed) { this._appEl_66.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
        this._query_Button_7_0.reset([this._Button_9_4]);
        this._ToolbarItem_7_3._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset([]);
        this._Item_24_4._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset([]);
        this._Item_24_4._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_32_1.dirty) {
        this._query_Button_32_1.reset([]);
        this._Item_32_4._buttons = this._query_Button_32_1;
        this._query_Button_32_1.notifyOnChanges();
      }
      if (this._query_Icon_32_2.dirty) {
        this._query_Icon_32_2.reset([]);
        this._Item_32_4._icons = this._query_Icon_32_2;
        this._query_Icon_32_2.notifyOnChanges();
      }
      if (this._query_Button_43_1.dirty) {
        this._query_Button_43_1.reset([]);
        this._Item_43_4._buttons = this._query_Button_43_1;
        this._query_Button_43_1.notifyOnChanges();
      }
      if (this._query_Icon_43_2.dirty) {
        this._query_Icon_43_2.reset([]);
        this._Item_43_4._icons = this._query_Icon_43_2;
        this._query_Icon_43_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_9_4.ngAfterContentInit(); }
      this._TextInput_29_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_24_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_37_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_32_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_43_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_63_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_66_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Toolbar_2_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:boolean = !this._ShowWhen_11_3.isMatch;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_11,'hidden-show-when',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Icon_14_3._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_14,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:boolean = !this._ShowWhen_14_4.isMatch;
    if (import6.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_14,'hidden-show-when',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_20_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_20,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._NgControlStatus_29_6.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_29_6.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_29_6.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_29_6.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_29_6.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_29_6.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_21:any = this._DateTime_37_4._disabled;
    if (import6.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_37,'datetime-disabled',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_23:any = this._NgControlStatus_37_8.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_37,'ng-untouched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_37_8.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_37,'ng-touched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_37_8.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_37,'ng-pristine',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_37_8.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_37,'ng-dirty',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_37_8.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_37,'ng-valid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_37_8.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_37,'ng-invalid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = import6.interpolate(1,'Entradas ',this.context.game.buyinns,'');
    if (import6.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setText(this._text_45,currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = import6.interpolate(1,'Rebuys ',this.context.game.rebuys,'');
    if (import6.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setText(this._text_48,currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = import6.interpolate(1,'Pote total R$ ',this.context.game.valueTotal,'');
    if (import6.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setText(this._text_51,currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_34:any = this._ItemReorder_55_3._enableReorder;
    if (import6.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_55,'reorder-enabled',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._ItemReorder_55_3._visibleReorder;
    if (import6.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_55,'reorder-visible',currVal_35);
      this._expr_35 = currVal_35;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_14_3.ngOnDestroy();
    this._NgModel_29_4.ngOnDestroy();
    this._TextInput_29_7.ngOnDestroy();
    this._DateTime_37_4.ngOnDestroy();
    this._NgModel_37_6.ngOnDestroy();
    this._ItemReorder_55_3.ngOnDestroy();
    this._Content_20_4.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.dismiss()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.game.description = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.game.date = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_1($event:any):boolean {
    this._appEl_37.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_37_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_37_2($event:any):boolean {
    this._appEl_37.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_37_4._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_ionItemReorder_55_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.reorderItem($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_63_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.validateInsertGame()) !== false);
    return (true && pd_0);
  }
  private _handle_click_66_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.preview()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_GameInsert0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<import5.GameInsert> {
  if ((renderType_GameInsert === (null as any))) { (renderType_GameInsert = viewUtils.createRenderComponentType('/Users/brunohenn/Projetos/PMNL2/.tmp/pages/games/game-insert.html',0,import18.ViewEncapsulation.None,styles_GameInsert,{})); }
  return new _View_GameInsert0(viewUtils,parentInjector,declarationEl);
}
class _View_GameInsert1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import62.ItemSliding;
  _query_Item_0_0:import23.QueryList<any>;
  _query_ItemOptions_0_1:import23.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _NgClass_2_4:import63.NgClass;
  _Item_2_5:import30.Item;
  _ItemContent_2_6:import30.ItemContent;
  _query_Label_2_0:import23.QueryList<any>;
  _query_Button_2_1:import23.QueryList<any>;
  _query_Icon_2_2:import23.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _ItemOptions_18_3:import62.ItemOptions;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Button_20_4:import24.Button;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Button_23_4:import24.Button;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _Button_26_4:import24.Button;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _map_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GameInsert1,renderType_GameInsert,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import64.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import62.ItemSliding((<_View_GameInsert0>this.parent)._List_55_4,this.renderer,new import40.ElementRef(this._el_0),this.parent.parentInjector.get(import46.NgZone));
    this._query_Item_0_0 = new import23.QueryList<any>();
    this._query_ItemOptions_0_1 = new import23.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import51.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._NgClass_2_4 = new import63.NgClass(this.parent.parentInjector.get(import59.IterableDiffers),this.parent.parentInjector.get(import65.KeyValueDiffers),new import40.ElementRef(this._el_2),this.renderer);
    this._Item_2_5 = new import30.Item(this.parent.parentInjector.get(import52.Form),this.parent.parentInjector.get(import39.Config),new import40.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_6 = new import30.ItemContent();
    this._query_Label_2_0 = new import23.QueryList<any>();
    this._query_Button_2_1 = new import23.QueryList<any>();
    this._query_Icon_2_2 = new import23.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_5,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),' ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'h2',(null as any));
    this.renderer.setElementAttribute(this._el_7,'item-right','');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n				',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_5.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_5,[
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_13,
        this._el_14,
        this._text_16
      ]
      ),
      [],
      [].concat([this._el_7])
    ]
    ,(null as any));
    this._text_17 = this.renderer.createText((null as any),'	\n			',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this.renderer.setElementAttribute(this._el_18,'side','left');
    this._ItemOptions_18_3 = new import62.ItemOptions(new import40.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText(this._el_18,'\n				',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'ion-button','');
    this._appEl_20 = new import2.AppElement(20,18,this,this._el_20);
    var compView_20:any = import44.viewFactory_Button0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Button_20_4 = new import24.Button((null as any),'',this.parent.parentInjector.get(import39.Config),new import40.ElementRef(this._el_20),this.renderer);
    this._appEl_20.initComponent(this._Button_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'Eliminado',(null as any));
    compView_20.create(this._Button_20_4,[[].concat([this._text_21])],(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n				',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'color','danger');
    this.renderer.setElementAttribute(this._el_23,'ion-button','');
    this._appEl_23 = new import2.AppElement(23,18,this,this._el_23);
    var compView_23:any = import44.viewFactory_Button0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Button_23_4 = new import24.Button((null as any),'',this.parent.parentInjector.get(import39.Config),new import40.ElementRef(this._el_23),this.renderer);
    this._appEl_23.initComponent(this._Button_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'Excluir',(null as any));
    compView_23.create(this._Button_23_4,[[].concat([this._text_24])],(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n				',(null as any));
    this._el_26 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'ion-button','');
    this._appEl_26 = new import2.AppElement(26,18,this,this._el_26);
    var compView_26:any = import44.viewFactory_Button0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Button_26_4 = new import24.Button((null as any),'',this.parent.parentInjector.get(import39.Config),new import40.ElementRef(this._el_26),this.renderer);
    this._appEl_26.initComponent(this._Button_26_4,[],compView_26);
    this._text_27 = this.renderer.createText((null as any),'Mais',(null as any));
    compView_26.create(this._Button_26_4,[[].concat([this._text_27])],(null as any));
    this._text_28 = this.renderer.createText(this._el_18,'\n			',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Item_0_0.reset([this._Item_2_5]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      [].concat([this._el_2]),
      [].concat([this._el_18])
    ]
    ,(null as any));
    this._map_0 = import6.pureProxy1((p0:any):{[key: string]:any} => {
      return {eliminado: p0};
    });
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this._expr_5 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_8 = import9.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import63.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgClass_2_4; }
    if (((token === import30.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Item_2_5; }
    if (((token === import30.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemContent_2_6; }
    if (((token === import24.Button) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Button_20_4; }
    if (((token === import24.Button) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Button_23_4; }
    if (((token === import24.Button) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Button_26_4; }
    if (((token === import62.ItemOptions) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemOptions_18_3; }
    if (((token === import62.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_0:any = this._map_0(this.context.$implicit.eliminado);
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_2_4.ngClass = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (!throwOnChange) { this._NgClass_2_4.ngDoCheck(); }
    const currVal_5:any = 'left';
    if (import6.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._ItemOptions_18_3.side = currVal_5;
      this._expr_5 = currVal_5;
    }
    changed = false;
    const currVal_8:any = 'danger';
    if (import6.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Button_23_4.color = currVal_8;
      changed = true;
      this._expr_8 = currVal_8;
    }
    if (changed) { this._appEl_23.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_5._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_5._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_18_3]);
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_23_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_26_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import6.interpolate(2,'',(this.context.index + 1),' ',this.context.$implicit.name,'');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import6.interpolate(1,'',this.context.$implicit.pointsPreview,'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import6.interpolate(1,'Rebuys ',this.context.$implicit.rebuys,'');
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_11,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import6.interpolate(1,'Prêmio R$ ',this.context.$implicit.prize,'');
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_15,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.eliminate(this.context.$implicit,this.context.index,this._ItemSliding_0_4)) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.removeItem(this.context.index,this._ItemSliding_0_4)) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.moreOptions(this.context.$implicit,this._ItemSliding_0_4)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GameInsert1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GameInsert1(viewUtils,parentInjector,declarationEl);
}
var renderType_GamePreview_Host:import0.RenderComponentType = (null as any);
class _View_GamePreview_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _GamePreview_0_4:import5.GamePreview;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GamePreview_Host0,renderType_GamePreview_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_GamePreview0(this.viewUtils,this.injector(0),this._appEl_0);
    this._GamePreview_0_4 = new import5.GamePreview(this.parentInjector.get(import11.ViewController),this.parentInjector.get(import17.NavParams));
    this._appEl_0.initComponent(this._GamePreview_0_4,[],compView_0);
    compView_0.create(this._GamePreview_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.GamePreview) && (0 === requestNodeIndex))) { return this._GamePreview_0_4; }
    return notFoundResult;
  }
}
function viewFactory_GamePreview_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_GamePreview_Host === (null as any))) { (renderType_GamePreview_Host = viewUtils.createRenderComponentType('',0,import18.ViewEncapsulation.None,[],{})); }
  return new _View_GamePreview_Host0(viewUtils,parentInjector,declarationEl);
}
export const GamePreviewNgFactory:import19.ComponentFactory<import5.GamePreview> = new import19.ComponentFactory<import5.GamePreview>('ng-component',viewFactory_GamePreview_Host0,import5.GamePreview);
const styles_GamePreview:any[] = [];
var renderType_GamePreview:import0.RenderComponentType = (null as any);
class _View_GamePreview0 extends import1.AppView<import5.GamePreview> {
  _el_0:any;
  _Header_0_3:import20.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _ToolbarTitle_2_4:import21.ToolbarTitle;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _Content_5_4:import28.Content;
  _text_6:any;
  _el_7:any;
  _List_7_3:import37.List;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgFor_9_6:import38.NgFor;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Button_12_4:import24.Button;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GamePreview0,renderType_GamePreview,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import20.Header(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import11.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-title',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import42.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(2),this._appEl_2);
    this._ToolbarTitle_2_4 = new import21.ToolbarTitle(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import20.Toolbar,(null as any)),this.parentInjector.get(import43.Navbar,(null as any)));
    this._appEl_2.initComponent(this._ToolbarTitle_2_4,[],compView_2);
    compView_2.create(this._ToolbarTitle_2_4,[[]],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_5 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_5 = new import2.AppElement(5,(null as any),this,this._el_5);
    var compView_5:any = import47.viewFactory_Content0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Content_5_4 = new import28.Content(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import48.App),this.parentInjector.get(import49.Keyboard),this.parentInjector.get(import46.NgZone),this.parentInjector.get(import11.ViewController,(null as any)),this.parentInjector.get(import50.Tabs,(null as any)));
    this._appEl_5.initComponent(this._Content_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_7_3 = new import37.List(this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import57.GestureController));
    this._text_8 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import58.TemplateRef_(this._appEl_9,viewFactory_GamePreview1);
    this._NgFor_9_6 = new import38.NgFor(this._appEl_9.vcRef,this._TemplateRef_9_5,this.parentInjector.get(import59.IterableDiffers),this.ref);
    this._text_10 = this.renderer.createText(this._el_7,'	\n	',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'full','');
    this.renderer.setElementAttribute(this._el_12,'ion-button','');
    this._appEl_12 = new import2.AppElement(12,5,this,this._el_12);
    var compView_12:any = import44.viewFactory_Button0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Button_12_4 = new import24.Button((null as any),'',this.parentInjector.get(import39.Config),new import40.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Button_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'Fechar',(null as any));
    compView_12.create(this._Button_12_4,[[].concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n',(null as any));
    compView_5.create(this._Content_5_4,[
      [],
      [].concat([
        this._text_6,
        this._el_7,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_3 = import9.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.ToolbarTitle) && (2 === requestNodeIndex))) { return this._ToolbarTitle_2_4; }
    if (((token === import20.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Header_0_3; }
    if (((token === import58.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import38.NgFor) && (9 === requestNodeIndex))) { return this._NgFor_9_6; }
    if (((token === import37.List) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._List_7_3; }
    if (((token === import24.Button) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Button_12_4; }
    if (((token === import28.Content) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Content_5_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_5_4.ngOnInit(); }
    changes = (null as any);
    const currVal_1:any = this.context.players;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_9_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_9_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_9_6.ngDoCheck(); }
    changed = false;
    const currVal_3:any = '';
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_12_4.full = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_12.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_12_4.ngAfterContentInit(); } }
    const currVal_0:any = this._Content_5_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_5,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_5_4.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.close()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_GamePreview0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<import5.GamePreview> {
  if ((renderType_GamePreview === (null as any))) { (renderType_GamePreview = viewUtils.createRenderComponentType('/Users/brunohenn/Projetos/PMNL2/.tmp/pages/games/game-preview.html',0,import18.ViewEncapsulation.None,styles_GamePreview,{})); }
  return new _View_GamePreview0(viewUtils,parentInjector,declarationEl);
}
class _View_GamePreview1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import30.Item;
  _ItemContent_0_5:import30.ItemContent;
  _query_Label_0_0:import23.QueryList<any>;
  _query_Button_0_1:import23.QueryList<any>;
  _query_Icon_0_2:import23.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GamePreview1,renderType_GamePreview,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import51.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import30.Item(this.parent.parentInjector.get(import52.Form),this.parent.parentInjector.get(import39.Config),new import40.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import30.ItemContent();
    this._query_Label_0_0 = new import23.QueryList<any>();
    this._query_Button_0_1 = new import23.QueryList<any>();
    this._query_Icon_0_2 = new import23.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4; }
    if (((token === import30.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import6.interpolate(3,'',(this.context.index + 1),' ',this.context.$implicit.name,' - ',this.context.$implicit.pointsFinal,'');
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_GamePreview1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GamePreview1(viewUtils,parentInjector,declarationEl);
}