/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './rules';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ionic-angular/navigation/view-controller';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from 'ionic-angular/components/app/app';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/components/tabs/tabs';
var renderType_RulesPage_Host:import0.RenderComponentType = (null as any);
class _View_RulesPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _RulesPage_0_4:import3.RulesPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RulesPage_Host0,renderType_RulesPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-rules',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RulesPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RulesPage_0_4 = new import3.RulesPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._RulesPage_0_4,[],compView_0);
    compView_0.create(this._RulesPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.RulesPage) && (0 === requestNodeIndex))) { return this._RulesPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_RulesPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_RulesPage_Host === (null as any))) { (renderType_RulesPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_RulesPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RulesPageNgFactory:import10.ComponentFactory<import3.RulesPage> = new import10.ComponentFactory<import3.RulesPage>('page-rules',viewFactory_RulesPage_Host0,import3.RulesPage);
const styles_RulesPage:any[] = [];
var renderType_RulesPage:import0.RenderComponentType = (null as any);
class _View_RulesPage0 extends import1.AppView<import3.RulesPage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import13.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import14.Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _el_106:any;
  _text_107:any;
  _text_108:any;
  _el_109:any;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _text_124:any;
  _text_125:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RulesPage0,renderType_RulesPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import17.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import19.App),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import13.ToolbarTitle(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Regras',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import21.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import14.Content(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import19.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import24.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'- Ocorrerá um evento por mês, entre os meses de janeiro e novembro.',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'- Em dezembro, ocorrerá a mesa final.',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'- Cada evento vale pontos do ranking conforme o número de pessoas que participaram dele, de acordo com a tabela de pontuação anexa (aba Pontuação).',(null as any));
    this._text_19 = this.renderer.createText((null as any),'	\n\n',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'- Os eventos de junho (metade do ano) e dezembro (mesa final) valem o dobro de pontos no ranking.',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'- Os eventos comuns ocorrerão com o mínimo de cinco e o máximo de doze jogadores. Caso haja mais de doze jogadores para uma data específica, terão preferência os primeiros colocados no ranking.',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'- Caso o número de jogadores não caiba na mesa, os jogadores serão separados em duas mesas, por sorteio. No momento em que o número de jogares total ainda vivos couber em uma só mesa, os jogadores serão aglutinados na mesma mesa, cada um levando as fichas que tiver. Os blinds aumentarão ao mesmo tempo em cada mesa.',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'- Para a escolha da data do evento comum de cada mês, será feita uma enquete via Doodle. O dia mais votado será o escolhido, exceto se nenhuma das pessoas desse dia puder ser o anfitrião. Como desempate para a escolha do dia, será usado o ranking, conforme critérios a seguir. O voto de cada pessoa vale o número de sua posição no ranking. Se a pessoa não possuir ranking, o seu voto vale a posição do último colocado + 1. O dia com menos pontos é que será escolhido no desempate. Se for o primeiro evento do ano, vale o ranking do ano anterior.\n',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'- A mesa final terá o mínimo de cinco e o máximo de oito jogadores. Caso haja mais de oito jogadores para uma data específica, terão preferência os primeiros colocados no ranking.\n',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'- Para a escolha da data da mesa final, será feita uma enquete via Doodle. Cada voto vale o número de pontos no ranking que o jogador possuir. O dia mais votado (conforme o critério anterior) será o escolhido, exceto se nenhuma das pessoas desse dia puderem ser o anfitrião. Como desempate para a escolha do dia, vale o dia com o maior número de pessoas. Como segundo critério, vale o dia que possuir a pessoa melhor ranqueada.',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'- Nos eventos comuns, cada jogador inicia com o mesmo número de fichas.',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'- Na mesa final, cada jogador incia com um número de fichas proporcional ao número de pontos no ranking que acumulou ao longo do ano.',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'- A inscrição de cada evento custa R$ 30,00, exceto a mesa final, que é gratuita.',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'- Se um jogador que confirmou presença (e não tiver desconfirmado até o horário marcado para o início do jogo) não estiver presente na hora em que a partida for iniciada, receberá as fichas normalmente e ficará dando fold automaticamente até a hora em que chegar (ou até a hora que terminar suas fichas, devido aos folds automáticos nos blinds). O jogador deverá pagar os R$ 30,00 para o PMNL independentemente de se aparecer até o final do jogo ou não. Caso ele apareça antes de terminar suas fichas, ele entra no jogo normalmente com as fichas que ainda tiver e ganhará pontos no ranking normalmente. Caso contrário, para fins de ranking, o torneio contará como se tivesse tido uma pessoa a menos e o dinheiro de inscrição do faltante vai para a mesa final. Se com isso o evento ficar com menos de cinco pessoas, contará no ranking como se fosse de cinco pessoas, mas o faltante não recebe ponto algum.\n',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'- Nos eventos normais, o valor de uma inscrição é guardada para a mesa final. A premiação em dinheiro é dada da seguinte forma:',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'- Se há menos de seis jogadores, o segundo colocado recebe seu dinheiro da inscrição de volta e o campeão do dia recebe o restante do dinheiro.',(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'- Se há de seis ou mais jogadores, o terceiro colocado recebe 10% do valor arrecadado, o segundo recebe 25% do valor arrecadado e o campeão do dia recebe 65% do valor arrecadado.',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_59 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'- Na mesa final, a premiação utilizada será a acumulada ao longo do ano. Com o dinheiro arrecadado, serão comprados troféus e/ou medalhas para os primeiros; o dinheiro restante irá para o pote da mesa final. O campeão da mesa final leva 65% do pote. O segundo lugar da mesa final leva 25% do pote. O terceiro lugar do ranking leva 10% do pote.',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'- Para a premiação da mesa final (troféu, medalha e dinheiro), o primeiro e segundo lugar são definidos exclusivamente pelo resultado da mesa final. As demais posições são definidas pelo ranking final.',(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_65 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'- Os eventos ocorrerão na modalidade Texas Hold\'em No-Limit, com os blinds iniciando em 5 & 10. Os blinds subirão a cada 20 minutos, conforme tabela específica abaixo.',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_68 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'- A partir do 4º nível de blind, haverá o ante, que é um valor mínimo que todos jogadores devem colocar, ainda que não entrem na rodada.',(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'- Até o 3º nível de blind, é possível o jogador fazer um rebuy uma única vez, caso tenha perdido todas as fichas, pagando 30 reais e ganhando o exato número de fichas que o jogador iniciou.',(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    this._el_74 = this.renderer.createElement((null as any),'ul',(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_76 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'1º: 5 & 10',(null as any));
    this._text_78 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_79 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'2º: 10 & 20',(null as any));
    this._text_81 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_82 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'3º: 20 & 40',(null as any));
    this._text_84 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_85 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'4º: 25 & 50 (ante 5)',(null as any));
    this._text_87 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_88 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'5º: 50 & 100 (ante 10)',(null as any));
    this._text_90 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_91 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'6º: 75 & 150 (ante 15)',(null as any));
    this._text_93 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_94 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'7º: 100 & 200 (ante 20)',(null as any));
    this._text_96 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_97 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'8º: 150 & 300 (ante 30)',(null as any));
    this._text_99 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_100 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'9º: 200 & 400 (ante 40)',(null as any));
    this._text_102 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_103 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_104 = this.renderer.createText(this._el_103,'10º: 250 & 500 (ante 50)',(null as any));
    this._text_105 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_106 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_107 = this.renderer.createText(this._el_106,'11º: 300 & 600 (ante 60)',(null as any));
    this._text_108 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_109 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_110 = this.renderer.createText(this._el_109,'12º: 400 & 800 (ante 80)',(null as any));
    this._text_111 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_112 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_113 = this.renderer.createText(this._el_112,'13º: 500 & 1000 (ante 100)',(null as any));
    this._text_114 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_115 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_116 = this.renderer.createText(this._el_115,'14º: 750 & 1500 (ante 150)',(null as any));
    this._text_117 = this.renderer.createText(this._el_74,'\n	',(null as any));
    this._el_118 = this.renderer.createElement(this._el_74,'li',(null as any));
    this._text_119 = this.renderer.createText(this._el_118,'15º: 1000 & 2000 (ante 200)',(null as any));
    this._text_120 = this.renderer.createText(this._el_74,'\n',(null as any));
    this._text_121 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    this._el_122 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'- Casos omissos serão decididos pela comissão organizadora',(null as any));
    this._text_124 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_16,
        this._el_17,
        this._text_19,
        this._el_20,
        this._text_22,
        this._el_23,
        this._text_25,
        this._el_26,
        this._text_28,
        this._el_29,
        this._text_31,
        this._el_32,
        this._text_34,
        this._el_35,
        this._text_37,
        this._el_38,
        this._text_40,
        this._el_41,
        this._text_43,
        this._el_44,
        this._text_46,
        this._el_47,
        this._text_49,
        this._el_50,
        this._text_52,
        this._el_53,
        this._text_55,
        this._el_56,
        this._text_58,
        this._el_59,
        this._text_61,
        this._el_62,
        this._text_64,
        this._el_65,
        this._text_67,
        this._el_68,
        this._text_70,
        this._el_71,
        this._text_73,
        this._el_74,
        this._text_121,
        this._el_122,
        this._text_124
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_125 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._text_124,
      this._text_125
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import14.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 124)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_RulesPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.RulesPage> {
  if ((renderType_RulesPage === (null as any))) { (renderType_RulesPage = viewUtils.createRenderComponentType('/Users/brunohenn/Projetos/PMNL2/.tmp/pages/rules/rules.html',0,import9.ViewEncapsulation.None,styles_RulesPage,{})); }
  return new _View_RulesPage0(viewUtils,parentInjector,declarationEl);
}